[colors.bright]
black = "#100F0F"
blue = "#4385BE"
cyan = "#3AA99F"
green = "#879A39"
magenta = "#CE5D97"
red = "#D14D41"
white = "#CECDC3"
yellow = "#D0A215"

[colors.cursor]
cursor = "#CECDC3"
text = "#CECDC3"

[colors.dim]
black = "#100F0F"
blue = "#205EA6"
cyan = "#24837B"
green = "#66800B"
magenta = "#A02F6F"
red = "#AF3029"
white = "#CECDC3"
yellow = "#AD8301"

[colors.normal]
black = "#100F0F"
blue = "#4385BE"
cyan = "#3AA99F"
green = "#879A39"
magenta = "#CE5D97"
red = "#D14D41"
white = "#CECDC3"
yellow = "#D0A215"

[colors.primary]
background = "#100F0F"
dim_foreground ="#878580" 
foreground ="#CECDC3" 
